language: php

php:
  - 5.5
#  - 5.6
#  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install: phpenv config-rm xdebug.ini

install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.1"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - mysql --version
  - mysql -e 'CREATE DATABASE `jkmssoft_yii2-counter_test`;';
  - cd tests
  - php codeception/bin/yii migrate/up --interactive=0
  - ~/.composer/vendor/bin/codecept build

script:
  - |
    cd web
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ..
    codecept run
